name: Build

on:
  push:
    branches-ignore:
      - '*'
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set ACTIONS_ALLOW_UNSECURE_COMMANDS
      run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1.0.0

    - name: Build Solution
      run: msbuild /p:Configuration=Release /m /p:Platform="Any CPU" Steamless.sln

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: software-artifact
        path: ./path/to/your/software/bin/Release
